# Generated by Django 4.1.5 on 2023-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(default=1),
        ),
    ]
