# Generated by Django 4.1.5 on 2023-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_quiz_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='marks_of_user',
            name='time_taken',
            field=models.IntegerField(default=1),
        ),
    ]
